In [27]:
#Mathematical Operations using Tensorflow

import tensorflow as tf

In [28]:
a= tf.constant([[3,4],[2,7]], name="a")
b=tf.constant([1,2], name="b")

In [29]:
c= tf.divide(a,b) #Computes Python style division of a by b
d= tf.div(a,b) #Returns a / b returns the quotient of a and b
e= tf.truediv(a,b) #Returns a / b evaluated in floating point. Will return error if both have different data types
f= tf.floordiv(a,b) #Returns a / b rounded down (except possibly towards zero for negative integers). Returns error if inputs are complex
g= tf.truncatediv(a,b) #Returns a Tensor. Has the same type as a
h= tf.floor_div(a,b) #Returns a Tensor. Has the same type as a

In [30]:
with tf.Session() as sess:
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))
    print(sess.run(f))
    print(sess.run(g))
    print(sess.run(h))

[[3.  2. ]
 [2.  3.5]]
[[3 2]
 [2 3]]
[[3.  2. ]
 [2.  3.5]]
[[3 2]
 [2 3]]
[[3 2]
 [2 3]]
[[3 2]
 [2 3]]


In [31]:
i= tf.add(a,b)

j=tf.constant([[67,7],[34,12]])

k= tf.add_n([a,i,j]) #Add n number of tensors mentioned as a list

In [32]:
with tf.Session() as sess:
    print("\n",sess.run(a))
    print("\n",sess.run(b))
    print("\n",sess.run(i))
    print("\n",sess.run(j))
    print("\n",sess.run(k))


 [[3 4]
 [2 7]]

 [1 2]

 [[4 6]
 [3 9]]

 [[67  7]
 [34 12]]

 [[74 17]
 [39 28]]


In [33]:
#Dot Product
l= tf.multiply(a,i)
m= tf.tensordot(a,i,1) #https://www.tensorflow.org/api_docs/python/tf/tensordot

with tf.Session() as sess:
    print(sess.run(l))
    print("\n",sess.run(m))
    

[[12 24]
 [ 6 63]]

 [[24 54]
 [29 75]]


In [34]:
#Data Types
sclr=999 
zero_0D= tf.zeros_like(sclr) #
one_0D= tf.ones_like(sclr)

with tf.Session() as sess:
    print(sess.run(zero_0D))
    print("\n",sess.run(one_0D))

0

 1


In [35]:
matrix= [[True, False, True],
       [False, False, False],
       [True, True, True]]  

tf.zeros_like(matrix) #2D tensor with all elements are False
tf.ones_like(matrix) #2D tensor with all elements are True

with tf.Session() as sess:
    print(sess.run(tf.zeros_like(matrix)))
    print("\n",sess.run(tf.ones_like(matrix)))
    


[[False False False]
 [False False False]
 [False False False]]

 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [36]:
#https://www.tensorflow.org/api_docs/python/tf/DType - Carious Data Types used in tensorFlow
import numpy as np
tf.ones([5,10], np.float32)

with tf.Session() as sess:
    print(sess.run(tf.ones([5,10], np.float32)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [37]:
#Variables

const= tf.constant([2,3], name="constant")
print(tf.get_default_graph().as_graph_def() )

#We have to create instance for the class tf.Variable

#Old way to create variables
n= tf.Variable(2, name="Scalar")
o= tf.Variable([[1,2],[3,4]], name="Matrix")
p= tf.Variable(tf.ones([20,10]))

node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 2
          }
        }
        tensor_content: "\003\000\000\000\004\000\000\000\002\000\000\000\007\000\000\000"
      }
    }
  }
}
node {
  name: "b"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "truediv/Cast"
  op: "Cast"
  input: "a"
  attr {
    key: "DstT"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "SrcT"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "truediv/Cast_1"
  op: "Cast"
  

In [38]:
#Recommended way to create variables
#tf.get_variabels(name, shape=None, dtype=None, initializer=None, regularizer=None,
#                trainable=True, collections=None, chaching_device=None, validate_shape=True, 
#                use_resource=None, custom_getter=None, constraint=None)

In [43]:
scl1= tf.get_variable("Scalar1", initializer=tf.constant(100))
matrx1= tf.get_variable("Matrix1", initializer=tf.constant([[1,0],[0,1]]))
massv_matrx1= tf.get_variable("Massive_matrix1", shape=(1000,50), initializer=tf.ones_initializer())

In [44]:
#Initialize variable

#We have to initialize variables before initializing them else we will get an error 
#FailedPreconditionError: Attempting to use uninitialized value
#To get the list of uninitialized variables we have to execute the below codes:
with tf.Session() as sess:
    print(sess.run(tf.report_uninitialized_variables()))

[b'Scalar' b'Matrix' b'Variable' b'Scalar01' b'Matrix01'
 b'Massive_matrix01' b'Scalar_1' b'Matrix_1' b'Variable_1' b'Scalar012'
 b'Scalar1' b'Matrix1' b'Massive_matrix1']


In [45]:
#To initialize variables we have to write
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [46]:
#To initialize a ssubset of variables
with tf.Session() as sess:
    sess.run(tf.variables_initializer([scl, matrx1]))

In [48]:
#To initialize each variables independently
with tf.Session() as sess:
    sess.run(massv_matrx1.initializer)

In [49]:
#Evaluate values of variables

#To obtain the value of any variable, we have to do it within a Session(just as we do with the Tensors for any rank)
massv_matrx2= tf.get_variable("Massive_matrix2", shape=(1000,50), initializer=tf.glorot_normal_initializer())

In [50]:
with tf.Session() as sess:
    sess.run(massv_matrx2.initializer)
    print(sess.run(massv_matrx2))

[[-5.1678508e-03  6.4531930e-02  7.3682979e-02 ...  2.4366552e-02
  -3.3857983e-02  3.5099518e-02]
 [-8.0960589e-03  8.2414091e-02 -9.2991339e-03 ...  4.2322485e-05
   1.0043974e-02  2.6718653e-03]
 [-4.1060533e-02 -5.8485554e-03  3.7289277e-02 ... -6.9892235e-02
  -3.9262585e-02  1.9772533e-02]
 ...
 [-8.1713475e-02 -1.1050471e-03 -3.2606244e-02 ... -3.6195785e-02
   1.6528577e-02  6.1658956e-02]
 [-6.1348653e-03  7.1618356e-02  5.4289129e-02 ...  4.4876598e-02
   3.4000441e-02 -3.1145599e-02]
 [-1.5403776e-02  5.9464006e-03 -1.2500992e-02 ... -4.7378421e-02
   3.3248603e-02  3.0866798e-02]]


In [51]:
#We can also fetch variables value using the below code

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(massv_matrx2.eval())

[[ 0.02578002  0.0112092  -0.02760454 ... -0.02644669 -0.01687422
  -0.01267762]
 [-0.0369631  -0.04852288  0.06562488 ... -0.02542177 -0.03033515
  -0.02084638]
 [ 0.00348308 -0.00344474  0.01049959 ...  0.00885793  0.0093137
  -0.05040877]
 ...
 [ 0.01571926 -0.01525904 -0.0566387  ...  0.01594963  0.05584946
  -0.04192933]
 [-0.01945242  0.00236771 -0.05508474 ...  0.00093471  0.0075521
   0.03368981]
 [ 0.05796298  0.04722494  0.06681641 ...  0.02504114 -0.02252532
   0.0408279 ]]


In [52]:
#Assign values to variables

q= tf.Variable(20)
q.assign(200)
with tf.Session() as sess:
    sess.run(q.initializer)
    print(q.eval())

20


In [53]:
#The above code creates assigns value of 20 to q instead of 200
#In order to assign the value of 200, we have to do it within session

with tf.Session() as sess:
    sess.run(q.assign(200))
    print(q.eval())

200


In [56]:
#assign() itself initializes the variable q for us. SO we do not need to do initialize it

#Create a variable with value 5
five= tf.get_variable("scalar5", initializer=tf.constant(5))
five_times_five= five.assign(five*5)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(five_times_five))
    print(sess.run(five_times_five))
    print(sess.run(five_times_five))
    print(sess.run(five_times_five))
    

25
125
625
3125


In [61]:
#Different Sessions in Tensorflow store different values of the variables as defined in the graph 
u = tf.Variable(10)

with tf.Session() as sess:
    sess.run(u.initializer)
    print(sess.run(u.assign_add(10)))
    print(sess.run(u.assign_sub(2)))

sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(u.initializer)
sess2.run(u.initializer)
print(sess1.run(u.assign_add(10)))
print(sess2.run(u.assign_sub(2)))
print(sess1.run(u.assign_add(100)))
print(sess2.run(u.assign_sub(50)))
sess1.close()
sess2.close()


20
18
20
8
120
-42


In [63]:
#Variable dependent on another variable
v= tf.Variable(tf.truncated_normal([100,20]))
w= tf.Variable(v*5)

In [73]:
with tf.Session() as sess:
    sess.run(w.initializer)
    print(sess.run(w))

[[ 6.4747626e-01  7.4096003e+00  7.3008685e+00 ... -4.1220040e+00
   6.1559410e+00 -9.4508761e-01]
 [ 3.1371484e+00  4.1287813e-01 -8.4507647e+00 ...  4.2785330e+00
  -1.0940245e+00 -1.6450399e+00]
 [ 2.4611829e-03 -4.2002760e-02 -6.6218204e+00 ...  2.5060177e+00
  -8.0040145e-01 -6.6769128e+00]
 ...
 [ 6.0477085e+00 -7.0281129e+00  3.4663978e-01 ... -3.1343975e+00
  -5.8803740e+00  2.6183498e+00]
 [ 5.2287674e+00  2.9487360e-01 -2.4135053e+00 ... -2.7651029e+00
  -6.2327557e+00  9.3042746e+00]
 [ 2.2122459e+00  9.2638129e-01 -2.3146532e+00 ... -1.6993466e-01
   1.7475996e+00  4.0548902e+00]]


In [68]:
#We should always use initialized_value() on the independent varaible before it is used to initialize the dependent variable
w= tf.Variable(v.initialized_value()*5)

In [71]:
with tf.Session() as sess:
    sess.run(w.initializer)
    print(sess.run(w))

[[-3.5179389  -2.3499174  -1.7281687  ... -4.640612   -1.9642208
   0.3084029 ]
 [-2.239652    1.2189678   5.8624697  ... -2.9329429  -5.0367393
   0.1714254 ]
 [-1.6462009  -0.5369278  -3.4658554  ...  6.3979063  -0.4112425
  -4.171026  ]
 ...
 [-2.6682644   4.765136   -2.2912683  ... -4.61277    -2.9479048
   0.78245944]
 [-6.347452   -6.044147    0.24225846 ...  4.6514335   3.5665514
   2.2332668 ]
 [ 4.249556    8.23491    -6.560136   ... -5.1099243   3.2322834
   6.3470693 ]]


In [76]:
#Interactive Sessions
#It is created as a default session where we can call the run() and eval() whithout explicitly calling the session everytime. 
#Though this looks convenient and easey but it creates problem when we have to work on multiple sessions 

sess=tf.InteractiveSession()
a=tf.constant(10)
b=tf.constant(30)
c=a*b
print(c.eval())
sess.close()

300


In [109]:
#Importing Data
#As mentioned earlier a TensorFlow program has two parts:
#    Step1: Create a graph
#    Step2: Evaluate variables and execute operations using a session

a= tf.placeholder(tf.float32, shape=[5])
b=tf.constant([12,13,1,23,5], tf.float32)
summation= a+b
with tf.Session() as sess:
    print(sess.run(summation, {a: [1,2,3,4,5]})) #declare the values of the placeholder
writer = tf.summary.FileWriter('graphs/placeholders', tf.get_default_graph())

SyntaxError: can't assign to operator (<ipython-input-109-512edf4ca7e3>, line 12)