In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' #No more warnings

In [2]:
import tensorflow as tf 

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [18]:
#Create Constant
#tf.constant(value, dtype=None, shape=None, name="constant", verify_shape=False)

#Constant of 1D Tensor i.e. Vector
a= tf.constant([10,20], name='Vector')

with tf.Session() as sess:
    print(sess.run(a))

[10 20]


In [19]:
#Constant of 2X2 tensor i.e. Matrix
b= tf.constant([[10,20],[30,40]], name='Matrix')

with tf.Session() as sess:
    print(sess.run(b))

[[10 20]
 [30 40]]


In [20]:
#To create Tensor with specific dimension and specific values
#tf.zeros([2,3], dtype=tf.int32, name=None)

#Create a Tensor 2x3 i.e. Matrix with zero as all elements
c= tf.zeros([2,3], dtype=tf.float32, name="Zero")
with tf.Session() as sess:
    print(sess.run(c))

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#Create a tensor of shape and type (unless specified) as tensor_shape but all the elements are zeros
tensor_shape= [[0,1],[2,3],[3,4],[4,5]]
d=tf.zeros_like(tensor_shape)

with tf.Session() as sess:
    print(sess.run(d))

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [23]:
#Create a tensor of any shape and all the elements are 1s
#tf.ones(shape, dtype=tf.float32, name=None)

e= tf.ones([3,5], dtype=tf.int32, name='Ones')

with tf.Session() as sess:
    print(sess.run(e))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
#Create a tensor of shape and type (unless specified) as tensor_shape but all the elements are 1s
#tf.ones_like(shape, name=None)

tensor_shape= [[0,1],[2,3],[3,4],[4,5]]
f=tf.ones_like(tensor_shape)

with tf.Session() as sess:
    print(sess.run(f))

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [26]:
#Create a Tensor and fill it with any scalar value
#tf.fill(dims, value, name=None)

g= tf.fill([5,4], 999)

with tf.Session() as sess:
    print(sess.run(g))

[[999 999 999 999]
 [999 999 999 999]
 [999 999 999 999]
 [999 999 999 999]
 [999 999 999 999]]


In [28]:
#Create Tensor with sequence of constants

#tf.lin_space(start, stop, num, name=None)

h= tf.lin_space(100.0, 200.0, 10, name="sequence")

with tf.Session() as s:
    print(s.run(h))


[100.       111.111115 122.22222  133.33333  144.44444  155.55556
 166.66666  177.77777  188.88889  200.      ]


In [41]:
#Create a Tensor sequence that increments by delta but does not include the limits

#tf.range([start], limit=None, delta=delta, dtype=None, name=None)

i= tf.range(10, limit=20, delta=1, dtype=tf.float32, name="seq1")
j= tf.range(50, limit=10, delta=-10, dtype=tf.float32, name="seq2")
limit=5
k= tf.range(limit)

with tf.Session() as s:
    print(s.run(i),'\n',s.run(j),'\n',s.run(k))


[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.] 
 [50. 40. 30. 20.] 
 [0 1 2 3 4]


In [62]:
#Generate Random conmstants from certain distributions

#tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
#Returns A tensor of the specified shape filled with random normal values

l= tf.random_normal([2,3], mean=0.0, stddev=1.0, dtype=tf.float32, seed=1, name="norm_dist")

#tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
#Returns A tensor of the specified shape filled with random truncated normal values.

m=tf.truncated_normal([3,4], mean=1.5, stddev=1.2, dtype=tf.float32, seed=123, name="trunc_norm")

#tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
#Returns A tensor of the specified shape filled with random uniform values.

n= tf.random_uniform([5,5], minval=10, maxval=100, dtype=tf.float32, seed=123, name="rand_uni")

#tf.random_shuffle(value, seed=None, name=None)
# tensor of same shape and type as value, shuffled along its first dimension
o= tf.random_shuffle(m, seed=tf.set_random_seed(123), name="rand_shuff")

#tf.random_crop(value, size, seed=None, name=None)
#Returns A cropped tensor of the same rank as value and shape size

p= tf.random_crop(m, size=[2,3], seed=123, name="crop")



with tf.Session() as s:
    print(s.run(l), "\n\n", s.run(m), "\n\n", s.run(n), "\n\n", s.run(p))
    

[[-0.6353692  -0.4363805  -0.99735504]
 [-0.2486418  -0.20590755 -1.030507  ]] 

 [[2.1831975  1.0788354  2.2319252  0.9189219 ]
 [0.6677643  1.7626889  0.14389801 1.0384336 ]
 [0.88161564 2.4888864  0.06121612 2.093206  ]] 

 [[81.96288   40.413055  76.45715   42.111546  64.870544 ]
 [91.27897   59.92342   68.45606   26.364609  83.97398  ]
 [64.95919   94.92102   15.3948345 17.199692  51.343346 ]
 [74.6177    28.962059  19.704628  38.494835  98.97165  ]
 [15.263632  91.942856  84.92684   98.36412   94.74072  ]] 

 [[ 1.7620294  3.6408837 -0.2725637]
 [ 2.974146   1.0282172  0.4127462]]
